### ISSUE TITLE
Notify on ReactiveViewModel doesn't seem to work. 

### ISSUE THREAD

**Issue by lifehug** [Stacked-Org/stacked#161]
Service code

```
class Preferences with ReactiveServiceMixin {

RxValue<int> _bar = RxValue<int>(initial: 65);
...

  Preferences() {
    listenToReactiveValues([_bar]);
  }

```

Model

```
class WeightSettingsModal extends ReactiveViewModel {
  @override
  List<ReactiveServiceMixin> get reactiveServices => [_preferences];
}

```

pubspec
```
provider: ^4.3.1
  flutter_slidable: "0.5.7"
  path_provider: ^1.6.11
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  splashscreen: ^1.2.0
...
  # state management
  stacked: ^1.7.6
  # # navigation
  auto_route:
  stacked_services:
  # inversion of control
  get_it: ^5.0.1
  observable_ish: ^2.1.4

```

I had to solve this on my own by listening to the stream and calling a custom notify() fucntion that notified listeners
