### ISSUE TITLE
Issue with registering the services is throwing boolean expression must not be null

### ISSUE THREAD

**Issue by ParthaGudivada** [Stacked-Org/stacked#166]
Upgraded Flutter to 1.22.1.  However when I try to run 

```
flutter pub run build_runner build --delete-conflicting-outputs
```

it is throwing an error 

```
[SEVERE] injectable_generator:injectable_builder on lib/services/third_party_service.dart:

Failed assertion: boolean expression must not be null
```

`third_party_service.dart` file is similar to what is mentioned it the readme

```
import 'package:injectable/injectable.dart';
import 'package:stacked_services/stacked_services.dart';

@module
abstract class ThirdPartyService {
  @lazySingleton
  NavigationService get navigationService;

  @lazySingleton
  DialogService get dialogService;

  @lazySingleton
  SnackbarService get snackbarService;
}

```

info pertaining to pubspec.yaml

```
dependencies:
  get_it: ^4.0.4
  injectable: ^1.0.4

dev_dependencies:
  auto_route_generator:  

  build_runner: ^1.10.3

  flutter_test:
    sdk: flutter

  injectable_generator: 

  json_serializable: ^3.4.0

dependency_overrides:
  analyzer: '0.40.4'
```
