### ISSUE TITLE
stacked_services > NavigationService /  auto_route issues

### ISSUE THREAD

**Issue by z0nekill** [Stacked-Org/stacked#182]
Hi there - 

I'm new to flutter so this could be completely my fault :/ but I've discovered your tutorials and have found them awesome. 

I'm having this issue where the NavigationService that's setup from this tutorial https://www.filledstacks.com/post/flutter-and-provider-architecture-using-stacked/ works, but when I'm navigating from one page to another using the locator pattern the `currentRoute` and `previousRoute` properties are empty, guards registered in the Router.dart class aren't being triggered and lastly, I can't seem to get the route params from the navigation service.

I have a feeling that maybe the Get library that's being used by the NavigationService hasn't registered `NavigatorState` properly (maybe I haven't done something)

Example.dart
```dart
  final NavigationService _navigationService = locator<NavigationService>();
  final CompanyService _companyService = locator<CompanyService>();

  @override
  List<ReactiveServiceMixin> get reactiveServices => [_companyService];

 Future<void> navigateToCompanyDetails(String tickerCode) async {
    try {
      await _navigationService
          .navigateTo(Routes.companyDetailView(tickerCode: tickerCode));
    } catch (error) {
      print(error);
    }
  }
```

Main.dart
```dart
import 'package:auto_route/auto_route_annotations.dart';
import 'package:quickfire_app/views/package.dart';

@MaterialAutoRouter(
  routes: <AutoRoute>[
    MaterialRoute(page: StartupView, initial: true),
    MaterialRoute(page: HomeView),
    MaterialRoute(path: "company/:tickerCode", page: CompanyDetailView)
  ],
)
class $Router {}
```

Module.dart
```dart
import 'package:injectable/injectable.dart';
import 'package:stacked_services/stacked_services.dart';
import './company_service.dart';

@module
abstract class QfServicesModule {
  @lazySingleton
  NavigationService get navigationService;
  @lazySingleton
  DialogService get dialogService;
  @lazySingleton
  CompanyService get companyService;
}
```

Locator.dart
```dart
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'locator.config.dart';

final locator = GetIt.instance;

@injectableInit
void setupLocator() => $initGetIt(locator);
```

Using:
```yaml
stacked:
    dependency: "direct main"
    description:
      name: stacked
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.6"
  stacked_services:
    dependency: "direct main"
    description:
      name: stacked_services
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.4+4"
  auto_route:
    dependency: "direct main"
    description:
      name: auto_route
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.9"
  get:
    dependency: "direct main"
    description:
      name: get
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.17.0"
  get_it:
    dependency: "direct main"
    description:
      name: get_it
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.1"
  injectable:
    dependency: "direct main"
    description:
      name: injectable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
```
