### ISSUE TITLE
[stacked_generator] Incompatible with code-generators that uses different versions of analyser

### ISSUE THREAD

**Issue by louisdup** [Stacked-Org/stacked#242]
Hello 

When I try to run:

flutter pub run build_runner build --delete-conflicting-outputs

I get "build_runner hangs on "Creating build script snapshot"

You can check here on related issue

build_runner hangs on "Creating build script snapshot

[](https://github.com/dart-lang/build/issues/2998)

``
Because stacked_generator >=0.2.0 depends on analyzer >=0.39.2 <0.41.2 and stacked_generator <0.2.0 depends on analyzer ^0.39.2, every version of stacked_generator requires analyzer >=0.39.2 <0.41.2.
And because analyzer >=0.32.4 <0.41.2 depends on glob ^1.0.3 and build_runner >=1.11.2 depends on glob ^2.0.0, stacked_generator is incompatible with build_runner >=1.11.2.
So, because app depends on both build_runner ^1.11.5 and stacked_generator any, version solving failed.
pub get failed (1; So, because app depends on both build_runner ^1.11.5 and stacked_generator any, version solving failed.)
``
Let me know if you need more info
Thanks

**Comment by FilledStacks** [comment]
I'll update glob now and push that up.

**Comment by FilledStacks** [comment]
Oh i don't use glob in the package. Can you post your pubspec.yaml file below please

**Comment by louisdup** [comment]
I need  build_runner 1.11.4,but build_runner needs  glob ^2.0.0 . but stacked_generator is incompatible with build_runner >=1.11.2

link to build runner snapshot hang issue 
https://github.com/dart-lang/build/issues/2998

![image](https://user-images.githubusercontent.com/17896235/110005032-ba1fbe00-7d20-11eb-8402-eb9b89bf9e3b.png)


```yml
name: app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
     sdk: '>=2.7.0 <3.0.0'

dependencies:
     flutter:
          sdk: flutter

     #State Management for now
     get: ^3.25.6
     stacked: ^1.9.5
     stacked_services: ^0.7.2
     stacked_hooks: ^0.1.3+2
     flutter_hooks: ^0.15.0

     # The following adds the Cupertino Icons font to your application.
     # Use with the CupertinoIcons class for iOS style icons.
     cupertino_icons: ^1.0.0

     shared_preferences: 0.5.12+4
     intl: ^0.16.1
     dio: 3.0.10
     dio_http_cache: ^0.2.11


     # UI Helpers
     material_dialog: ^0.0.9
     pin_code_fields: ^6.1.0
     carousel_slider: ^3.0.0
     flutter_easyloading: ^2.2.2


     fluttertoast: ^7.1.6

     cached_network_image: ^2.5.0
     flutter_cache_manager: ^2.1.1
     objectbox: ^0.12.0
     objectbox_flutter_libs: any
     path_provider: ^1.6.18

dev_dependencies:
     flutter_test:
          sdk: flutter

     build_runner: ^1.11.5
     stacked_generator: 
     objectbox_generator:

     # Ignored for now
     #json_serializable: ^3.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
     # The following line ensures that the Material Icons font is
     # included with your application, so that you can use the icons in
     # the material Icons class.
     uses-material-design: true

     # To add assets to your application, add an assets section, like this:
     assets:
          - assets/images/

     # An image asset can refer to one or more resolution-specific "variants", see
     # https://flutter.dev/assets-and-images/#resolution-aware.

     # For details regarding adding assets from package dependencies, see
     # https://flutter.dev/assets-and-images/#from-packages

     # To add custom fonts to your application, add a fonts section here,
     # in this "flutter" section. Each entry in this list should have a
     # "family" key with the font family name, and a "fonts" key with a
     # list giving the asset and other descriptors for the font. For
     # example:
     fonts:

     #
     # For details regarding fonts from package dependencies,
     # see https://flutter.dev/custom-fonts/#from-packages

```
