### ISSUE TITLE
Dependencies issues (get_it)

### ISSUE THREAD

**Issue by lcsvcn** [Stacked-Org/stacked#258]
**flutter pub get**
> Running "flutter pub get" in myApp...                          
> Because stacked 1.9.5 depends on get_it ^5.0.6 and no versions of stacked match >1.9.5 <2.0.0, stacked ^1.9.5 requires get_it ^5.0.6.
> 
> So, because myApp depends on both get_it ^6.0.0 and stacked ^1.9.5, version solving failed.
> pub get failed (1; So, because myApp depends on both get_it ^6.0.0 and stacked ^1.9.5, version solving failed.)
> exit code 1

At **pubspec.yaml**:
```
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  get_it: ^6.0.0
  stacked: ^1.9.5
```

**flutter --version**
> 
> Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision c5a4b4029c (6 days ago) • 2021-03-04 09:47:48 -0800
> Engine • revision 40441def69
> Tools • Dart 2.12.0
