### ISSUE TITLE
[bug]: Error: No named parameter with the name 'vsync'.

### ISSUE THREAD

**Issue by Al-Krause-ex** [Stacked-Org/stacked#918]
### Errors:
_pub.dev/stacked-3.2.0/lib/src/view_models/ui/skeleton_loader.dart:106:19: Error: No named parameter with the name 'vsync'.
                  vsync: this,
                  ^^^^^_
_lib/src/widgets/animated_size.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^_

### My code:
**lib/core/app/routes.dart**
```import 'package:stacked/stacked_annotations.dart';
import 'package:todos_frontend/presentation/show_todos/show_todos_view.dart';

@StackedApp(routes: [
 AdaptiveRoute(page: ShowTodosView, initial: true),
])
class App {}
```

**routes.router.dart**
```// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// StackedNavigatorGenerator
// **************************************************************************

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/material.dart';
import 'package:stacked/stacked.dart' as _i1;
import 'package:stacked_services/stacked_services.dart' as _i3;
import 'package:todos_frontend/presentation/show_todos/show_todos_view.dart'
    as _i2;

class Routes {
  static const showTodosView = '/';

  static const all = <String>{showTodosView};
}

class StackedRouter extends _i1.RouterBase {
  final _routes = <_i1.RouteDef>[
    _i1.RouteDef(
      Routes.showTodosView,
      page: _i2.ShowTodosView,
    )
  ];

  final _pagesMap = <Type, _i1.StackedRouteFactory>{
    _i2.ShowTodosView: (data) {
      return _i1.buildAdaptivePageRoute<dynamic>(
        builder: (context) => const _i2.ShowTodosView(),
        settings: data,
      );
    }
  };

  @override
  List<_i1.RouteDef> get routes => _routes;
  @override
  Map<Type, _i1.StackedRouteFactory> get pagesMap => _pagesMap;
}

extension NavigatorStateExtension on _i3.NavigationService {
  Future<dynamic> navigateToShowTodosView([
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  ]) async {
    return navigateTo<dynamic>(Routes.showTodosView,
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }

  Future<dynamic> replaceWithShowTodosView([
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  ]) async {
    return replaceWith<dynamic>(Routes.showTodosView,
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }
}
```

**main.dart**
```import 'package:flutter/material.dart';
import 'package:stacked_services/stacked_services.dart';

import 'core/app/routes.router.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fullstack Todo App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      navigatorKey: StackedService.navigatorKey,
      onGenerateRoute: StackedRouter().onGenerateRoute,
    );
  }
}
```

### Version
**Flutter version 3.9.0-0.2.pre**
**Dart version 3.0.0 (build 3.0.0-290.3.beta)**

### To reproduce

1. Create routes.dart
2. run build_runner
3. add in main.dart (navigatorKey: StackedService.navigatorKey, onGenerateRoute: StackedRouter().onGenerateRoute,)
4. run

**Comment by FilledStacks** [comment]
Hi, thanks for opening a well structured issue. Next time when you add code please use

```

```dart
Your code here will be formatted as code. Don't add ` around every line. And end with "```" as well. 
```



In terms of the bud I'll check this out. What version of the stacked_cli are you using to generate the app?

**Comment by Al-Krause-ex** [comment]
> Hi, thanks for opening a well structured issue. Next time when you add code please use
> 
> ```
> 
> ```dart
> Your code here will be formatted as code. Don't add ` around every line. And end with "```" as well. 
> ```
> 
> In terms of the bud I'll check this out. What version of the stacked_cli are you using to generate the app?

Thanks for the advice!

### My pubspec.yaml
```
environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  either_dart: ^0.3.0
  flutter_hooks: ^0.18.6
  get_it: ^7.2.0
  injectable: ^2.1.1
  stacked: ^3.2.0
  stacked_services: ^1.0.0
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.1
  very_good_analysis: ^4.0.0+1
  stacked_generator: ^1.0.0
  injectable_generator: ^2.1.5
  retrofit_generator: ^6.0.0+1
```

**Comment by Al-Krause-ex** [comment]
Now I tried to create an application through stacked_cli, having previously installed it (**stacked_cli: ^1.5.1**)

Ran the command: `stacked create app my_app`

I tried to run the project through the emulator / physical. device, same problem

### main.dart
```
import 'package:flutter/material.dart';
import 'package:my_app/app/app.bottomsheets.dart';
import 'package:my_app/app/app.dialogs.dart';
import 'package:my_app/app/app.locator.dart';
import 'package:my_app/app/app.router.dart';
import 'package:my_app/ui/common/app_colors.dart';
import 'package:stacked_services/stacked_services.dart';

void main() {
  setupLocator();
  setupDialogUi();
  setupBottomSheetUi();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: Theme.of(context).copyWith(
        primaryColor: kcBackgroundColor,
        focusColor: kcPrimaryColor,
        textTheme: Theme.of(context).textTheme.apply(
              bodyColor: Colors.black,
            ),
      ),
      initialRoute: Routes.startupView,
      onGenerateRoute: StackedRouter().onGenerateRoute,
      navigatorKey: StackedService.navigatorKey,
      navigatorObservers: [
        StackedService.routeObserver,
      ],
    );
  }
}
```

### lib/app/app.dart
```
import 'package:my_app/ui/bottom_sheets/notice/notice_sheet.dart';
import 'package:my_app/ui/dialogs/info_alert/info_alert_dialog.dart';
import 'package:my_app/ui/views/home/home_view.dart';
import 'package:my_app/ui/views/startup/startup_view.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
// @stacked-import

@StackedApp(
  routes: [
    MaterialRoute(page: HomeView),
    MaterialRoute(page: StartupView),
    // @stacked-route
  ],
  dependencies: [
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: NavigationService),
    // @stacked-service
  ],
  bottomsheets: [
    StackedBottomsheet(classType: NoticeSheet),
    // @stacked-bottom-sheet
  ],
  dialogs: [
    StackedDialog(classType: InfoAlertDialog),
    // @stacked-dialog
  ],
)
class App {}
```

### pubspec.yaml
```
name: my_app
description: An app build with the stacked framework
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  stacked: ^3.2.0
  stacked_services: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

  stacked_generator: ^1.0.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true
```
