### ISSUE TITLE
[bug]: Installation 

### ISSUE THREAD

**Issue by moha-b** [Stacked-Org/stacked#968]
### Describe the bug

I am trying to import stacked to my project for the first time so I just run the command for [pub.dev](https://pub.dev/packages/stacked)
```
flutter pub add stacked
```
but the terminal keeps giving me this :
"Because stacked depends on stacked, version solving failed." 

I tried to put it in the `dependencies` directly 
```
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  stacked:
```
but it can't even identify the package
```
Error on line 37, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
37 │   stacked:
   │   ^^^^^^^
   ╵
```
versions
```
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  
# Flutter 3.10.0 
```

### To reproduce

1 - create a new flutter project from android studio 
2 - make the project for all platforms (web, Linx, windows, android, etc)
3 - add `stacked` to pubspec.yaml 
4 - run pub get

### Screenshots

![image](https://github.com/Stacked-Org/stacked/assets/73842931/ce3816d1-73d7-4010-bb7f-650d35e18ab6)
![image](https://github.com/Stacked-Org/stacked/assets/73842931/fe32584d-c50c-452d-ab0c-1a821bc9c303)
