### ISSUE TITLE
[docs]: No documentation on how to use InitializableSingleton

### ISSUE THREAD

**Issue by eb-so** [Stacked-Org/stacked#984]
### Describe the missing piece of documentation

After a little bit of digging, I found out how to use it from this [issue](https://github.com/Stacked-Org/stacked/issues/728)

however, I'm facing an issue

```

[SEVERE] stacked_generator:stackedLocatorGenerator on lib/app.dart:

InvalidGeneratorInputException: message: At least one paramter is requerd for FactoryWithParam registration 
 todo: 
 element: null

```

this is the service
```
class DataCache extends InitializableDependency {
  // ... code

  @override
  Future<void> init() async {
    final appDocumentDir = await getApplicationDocumentsDirectory();
    Hive.init(appDocumentDir.path);

    _registerAdapters();
  }
}

```

I registered like this
```
    InitializableSingleton(
      classType: DataCache,
    ),
```
